/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: 4e26630e7015c31436ff30f21ea5d15d)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	SITE_ORIGIN: "https://mandulaj.hu";
	TURNSTILE_HOSTNAMES: "mandulaj.hu";
	VISITOR_SALT: string;
	TURNSTILE_SECRET_KEY: string;
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_CHAT_ID: string;
	TELEGRAM_THREAD_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_ORIGIN" | "TURNSTILE_HOSTNAMES" | "VISITOR_SALT" | "TURNSTILE_SECRET_KEY" | "TELEGRAM_BOT_TOKEN" | "TELEGRAM_CHAT_ID" | "TELEGRAM_THREAD_ID">> {}
}
