#!/usr/bin/env tsx
/**
 * Generates the per-page accent stylesheet.
 *
 * The Kassák direction gives each page one of four accents. "Random" would be
 * wrong: a note must not change colour between builds, or its identity flickers
 * and its OG card stops matching the page. So the accent is derived from a hash
 * of the slug — arbitrary-looking, identical forever, and stable across machines.
 *
 * Output is plain CSS keyed on `body[data-slug]`, which Quartz already renders.
 * No JavaScript, no flash of the wrong colour on first paint, and SPA navigation
 * reapplies it for free because micromorph swaps the attribute.
 */
import fs from "node:fs/promises"
import path from "node:path"
import { c } from "./lib.js"

const REPO = path.resolve(import.meta.dirname, "..")
const MANIFEST = path.join(REPO, ".publish-manifest.json")
const OUT = path.join(REPO, "quartz-custom/theme/_accents.generated.scss")

/**
 * Six accents. Every value is solved to clear WCAG AA (4.5:1) against its own
 * mode's background, holding hue and saturation constant — so the light and
 * dark values of a pair are the same colour at different lightness, not two
 * different colours.
 *
 * Hues are spread deliberately (7° 39° 164° 226° 264° 341°) so consecutive
 * notes are unlikely to look related. vermilion is the Kassák red from the
 * original comps.
 *
 *   name         hue    light  (on #F2EFE6)   dark (on #16130F)
 *   vermilion      7°   #CD311D  4.51:1       #E24531  4.52:1
 *   ochre         39°   #92640D  4.51:1       #C98A12  6.28:1
 *   verdigris    164°   #3F6B5F  5.25:1       #508879  4.53:1
 *   ultramarine  226°   #1F3FA8  7.82:1       #5777E0  4.51:1
 *   aubergine    264°   #5B3A8C  7.52:1       #906DC3  4.55:1
 *   oxblood      341°   #7A2540  8.43:1       #CC557B  4.54:1
 *
 * Paper-on-accent (the ID badge) also clears AA for all six.
 *
 * Adding a seventh: solve it the same way rather than eyeballing. The raw
 * comp colours did NOT pass — ochre was 2.56:1 in light mode.
 */
export const ACCENTS = {
  vermilion: { light: "#CD311D", dark: "#E24531" },
  ochre: { light: "#92640D", dark: "#C98A12" },
  verdigris: { light: "#3F6B5F", dark: "#508879" },
  ultramarine: { light: "#1F3FA8", dark: "#5777E0" },
  aubergine: { light: "#5B3A8C", dark: "#906DC3" },
  oxblood: { light: "#7A2540", dark: "#CC557B" },
} as const

/**
 * Uncategorised pages. Ink rather than a hue, so "no colour" reads as "not
 * filed" instead of implying a category that does not exist.
 */
export const NEUTRAL = { light: "#3A342B", dark: "#B8AF9C" } as const

export type AccentName = keyof typeof ACCENTS
const NAMES = Object.keys(ACCENTS) as AccentName[]

/** FNV-1a. Small, dependency-free, and stable across Node versions. */
function hash(s: string): number {
  let h = 0x811c9dc5
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i)
    h = Math.imul(h, 0x01000193) >>> 0
  }
  return h >>> 0
}

export function accentFor(slug: string): AccentName {
  return NAMES[hash(slug) % NAMES.length]
}

/** Slightly translucent accent, for rules and highlight washes. */
function mix(hex: string, pct: number): string {
  return `color-mix(in srgb, ${hex} ${pct}%, transparent)`
}

export async function generateAccents(manifestPath = MANIFEST, outputPath = OUT) {
  const manifest = JSON.parse(await fs.readFile(manifestPath, "utf8")) as {
    // `accent` may be "neutral" for uncategorised pages, which is deliberately
    // NOT an AccentName — the palette has six hues and neutral is the absence
    // of one.
    notes: { slug: string; accent?: AccentName | "neutral"; zk?: string }[]
  }

  // The manifest is authoritative: sync.ts assigns accents (balanced, sticky,
  // frontmatter-pinnable) and records them. accentFor() is only the fallback
  // for a manifest written before accents existed.
  const grouped = new Map<AccentName, string[]>(NAMES.map((n) => [n, []]))
  const neutral: string[] = []
  for (const { slug, accent } of manifest.notes) {
    if (accent === "neutral" || !accent || !(accent in ACCENTS)) {
      neutral.push(slug)
      continue
    }
    grouped.get(accent as AccentName)!.push(slug)
  }

  const ids = manifest.notes
    .filter((n) => n.zk)
    .map((n) => `body[data-slug="${n.slug}"] { --zk-id: "${n.zk}"; }`)

  const lines: string[] = [
    "// ─────────────────────────────────────────────────────────────────────",
    "// GENERATED by `npm run sync` (scripts/gen-accents.ts). Do not edit.",
    "// Per-page accent, derived deterministically from the slug.",
    "// ─────────────────────────────────────────────────────────────────────",
    "",
  ]

  for (const name of NAMES) {
    const slugs = grouped.get(name)!
    if (!slugs.length) continue
    const sel = slugs.map((s) => `body[data-slug="${s}"]`).join(",\n")
    const { light, dark } = ACCENTS[name]
    lines.push(
      `// ${name} — ${slugs.length} page(s)`,
      `${sel} {`,
      `  --accent: ${light};`,
      `  --accent-name: "${name}";`,
      `  --secondary: ${light};`,
      `  --tertiary: ${light};`,
      `  --accent-wash: ${mix(light, 8)};`,
      `  --accent-rule: ${mix(light, 55)};`,
      `}`,
      "",
      `:root[saved-theme="dark"] {`,
      `  ${sel.split("\n").join("\n  ")} {`,
      `    --accent: ${dark};`,
      `    --secondary: ${dark};`,
      `    --tertiary: ${dark};`,
      `    --accent-wash: ${mix(dark, 14)};`,
      `    --accent-rule: ${mix(dark, 55)};`,
      `  }`,
      `}`,
      "",
    )
  }

  if (neutral.length) {
    const sel = neutral.map((s) => `body[data-slug="${s}"]`).join(",\n")
    lines.push(
      `// uncategorised — ${neutral.length} page(s)`,
      `${sel} {`,
      `  --accent: ${NEUTRAL.light};`,
      `  --accent-name: "neutral";`,
      `  --secondary: ${NEUTRAL.light};`,
      `  --tertiary: ${NEUTRAL.light};`,
      `  --accent-wash: ${mix(NEUTRAL.light, 8)};`,
      `  --accent-rule: ${mix(NEUTRAL.light, 55)};`,
      `}`,
      "",
      `:root[saved-theme="dark"] {`,
      `  ${sel.split("\n").join("\n  ")} {`,
      `    --accent: ${NEUTRAL.dark};`,
      `    --secondary: ${NEUTRAL.dark};`,
      `    --tertiary: ${NEUTRAL.dark};`,
      `    --accent-wash: ${mix(NEUTRAL.dark, 14)};`,
      `    --accent-rule: ${mix(NEUTRAL.dark, 55)};`,
      `  }`,
      `}`,
      "",
    )
  }

  lines.push("// Per-page display IDs (derived from slug, pinnable via `zk:`).", ...ids, "")

  await fs.writeFile(outputPath, lines.join("\n"), "utf8")

  const summary =
    NAMES.map((n) => `${n} ${grouped.get(n)!.length}`).join(" · ") + ` · neutral ${neutral.length}`
  console.log(c.dim(`  accents → ${summary}`))
}

// Only run when invoked directly, so sync.ts can import accentFor().
if (process.argv[1] && path.resolve(process.argv[1]).endsWith("gen-accents.ts")) {
  await generateAccents()
}
