/** Shared helpers for the API Worker. `Env` is generated by `wrangler types`. */

export const json = (data: unknown, status = 200, extra: HeadersInit = {}) =>
  new Response(JSON.stringify(data), {
    status,
    headers: { "content-type": "application/json; charset=utf-8", ...extra },
  })

export const bad = (message: string, status = 400) => json({ error: message }, status)

/**
 * A scoped pseudonymous id for a visitor, keyed with a required secret.
 *
 * HMAC prevents precomputation if the database is exposed. The scope keeps a
 * like identifier from being correlated with a rate-limit identifier.
 */
export async function visitorId(req: Request, secret: string, scope: string): Promise<string> {
  if (!secret) throw new Error("VISITOR_SALT is not configured")
  const ip = req.headers.get("cf-connecting-ip") ?? "0.0.0.0"
  const ua = req.headers.get("user-agent") ?? ""
  const encoder = new TextEncoder()
  const key = await crypto.subtle.importKey(
    "raw",
    encoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  )
  const signature = await crypto.subtle.sign("HMAC", key, encoder.encode(`${scope}|${ip}|${ua}`))
  return [...new Uint8Array(signature)]
    .slice(0, 16)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")
}

/** Daily key for short-lived rate-limit rows. */
export function rateLimitScope(action: string, now = Date.now()): string {
  return `rate:${action}:${Math.floor(now / 86_400_000)}`
}

/** Sliding-window limiter backed by D1. Returns true when the caller is over. */
export async function isRateLimited(
  db: D1Database,
  visitor: string,
  action: string,
  limit: number,
  windowMs: number,
): Promise<boolean> {
  const now = Date.now()
  const since = now - windowMs
  // The decision and insert are one SQLite statement. D1 serialises writes, so
  // concurrent requests cannot both observe a free slot and both consume it.
  const inserted = await db
    .prepare(
      `INSERT INTO rate_limit (visitor, action, created_at)
       SELECT ?, ?, ?
        WHERE (SELECT COUNT(*) FROM rate_limit
                WHERE visitor = ? AND action = ? AND created_at > ?) < ?`,
    )
    .bind(visitor, action, now, visitor, action, since, limit)
    .run()

  // Opportunistic prune so the table cannot grow without bound. This does not
  // affect the decision above, so it is safe as a separate awaited statement.
  await db
    .prepare("DELETE FROM rate_limit WHERE created_at < ?")
    .bind(now - 86_400_000)
    .run()
  return inserted.meta.changes === 0
}

/** Slugs come from the client, so constrain them to what sync can produce. */
export const isValidSlug = (s: unknown): s is string =>
  typeof s === "string" && s.length > 0 && s.length <= 120 && /^[a-z0-9][a-z0-9-]*$/.test(s)

/**
 * Verifies a Turnstile token. Fails CLOSED: if the secret is unset or the
 * verify call errors, the submission is rejected rather than let through.
 */
export async function verifyTurnstile(
  secret: string,
  token: unknown,
  ip: string,
  expectedHostname: string,
  expectedAction: string,
): Promise<boolean> {
  if (!secret) return false
  if (typeof token !== "string" || !token) return false
  try {
    const body = new FormData()
    body.append("secret", secret)
    body.append("response", token)
    body.append("remoteip", ip)
    const res = await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", {
      method: "POST",
      body,
    })
    const data = (await res.json()) as { success?: boolean; hostname?: string; action?: string }
    return (
      data.success === true && data.hostname === expectedHostname && data.action === expectedAction
    )
  } catch {
    return false
  }
}

/**
 * Fire-and-forget Telegram notification. Never throws and never blocks the
 * response — a comment must still be accepted if Telegram is unreachable.
 */
export async function notifyTelegram(env: Env, text: string): Promise<void> {
  const { TELEGRAM_BOT_TOKEN: token, TELEGRAM_CHAT_ID: chat } = env
  if (!token || !chat) return
  try {
    await fetch(`https://api.telegram.org/bot${token}/sendMessage`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        chat_id: chat,
        text,
        parse_mode: "HTML",
        disable_web_page_preview: true,
      }),
    })
  } catch {
    /* notification is best-effort */
  }
}

/** Escapes text for safe interpolation into Telegram's HTML parse mode. */
export const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
