/** Shared helpers for the API Worker. `Env` is generated by `wrangler types`. */

export const json = (data: unknown, status = 200, extra: HeadersInit = {}) =>
  new Response(JSON.stringify(data), {
    status,
    headers: { "content-type": "application/json; charset=utf-8", ...extra },
  })

export const bad = (message: string, status = 400) => json({ error: message }, status)

/**
 * A scoped pseudonymous id for a visitor, keyed with a required secret.
 *
 * HMAC prevents precomputation if the database is exposed. The scope keeps a
 * like identifier from being correlated with a rate-limit identifier.
 */
export async function visitorId(req: Request, secret: string, scope: string): Promise<string> {
  if (!secret) throw new Error("VISITOR_SALT is not configured")
  const ip = req.headers.get("cf-connecting-ip") ?? "0.0.0.0"
  const ua = req.headers.get("user-agent") ?? ""
  const encoder = new TextEncoder()
  const key = await crypto.subtle.importKey(
    "raw",
    encoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  )
  const signature = await crypto.subtle.sign("HMAC", key, encoder.encode(`${scope}|${ip}|${ua}`))
  return [...new Uint8Array(signature)]
    .slice(0, 16)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")
}

/** Daily key for short-lived rate-limit rows. */
export function rateLimitScope(action: string, now = Date.now()): string {
  return `rate:${action}:${Math.floor(now / 86_400_000)}`
}

/** Sliding-window limiter backed by D1. Returns true when the caller is over. */
export async function isRateLimited(
  db: D1Database,
  visitor: string,
  action: string,
  limit: number,
  windowMs: number,
): Promise<boolean> {
  const now = Date.now()
  const since = now - windowMs
  // The decision and insert are one SQLite statement. D1 serialises writes, so
  // concurrent requests cannot both observe a free slot and both consume it.
  const inserted = await db
    .prepare(
      `INSERT INTO rate_limit (visitor, action, created_at)
       SELECT ?, ?, ?
        WHERE (SELECT COUNT(*) FROM rate_limit
                WHERE visitor = ? AND action = ? AND created_at > ?) < ?`,
    )
    .bind(visitor, action, now, visitor, action, since, limit)
    .run()

  // Opportunistic prune so the table cannot grow without bound. This does not
  // affect the decision above, so it is safe as a separate awaited statement.
  await db
    .prepare("DELETE FROM rate_limit WHERE created_at < ?")
    .bind(now - 86_400_000)
    .run()
  return inserted.meta.changes === 0
}

/** Slugs come from the client, so constrain them to what sync can produce. */
export const isValidSlug = (s: unknown): s is string =>
  typeof s === "string" && s.length > 0 && s.length <= 120 && /^[a-z0-9][a-z0-9-]*$/.test(s)

/**
 * Verifies a Turnstile token. Fails CLOSED: if the secret is unset or the
 * verify call errors, the submission is rejected rather than let through.
 */
/** Turnstile tokens are ~600 chars; anything far larger is not one. */
const MAX_TOKEN_LEN = 4096
const SITEVERIFY_TIMEOUT_MS = 8000

export interface TurnstileResult {
  ok: boolean
  /** Populated on failure, for server-side logging only. Never sent to a client. */
  reason?: string
}

/**
 * Verifies a Turnstile token against three independent conditions.
 *
 * All three must hold, because `success` alone is weaker than it looks:
 *
 *  1. `success` — the challenge was actually solved.
 *  2. `action` — the token came from the comment form, not from some other
 *     widget on the site. Without this a token minted by any other form could
 *     be replayed here.
 *  3. `hostname` — the widget was solved on a host we serve. Without this
 *     someone can embed our sitekey on their own page, farm tokens there, and
 *     post with them.
 *
 * Fails CLOSED on every error path: no secret, malformed token, network
 * failure, timeout, non-200, unparseable body.
 */
export async function verifyTurnstile(
  secret: string | undefined,
  token: unknown,
  ip: string,
  allowedHostnames: string[],
  expectedAction: string,
): Promise<TurnstileResult> {
  if (!secret) return { ok: false, reason: "no secret configured" }
  if (typeof token !== "string" || !token) return { ok: false, reason: "missing token" }
  if (token.length > MAX_TOKEN_LEN) return { ok: false, reason: "token too long" }
  if (allowedHostnames.length === 0) return { ok: false, reason: "no allowed hostnames" }

  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), SITEVERIFY_TIMEOUT_MS)
  try {
    const body = new FormData()
    body.append("secret", secret)
    body.append("response", token)
    body.append("remoteip", ip)

    const res = await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", {
      method: "POST",
      body,
      signal: controller.signal,
    })
    if (!res.ok) return { ok: false, reason: `siteverify HTTP ${res.status}` }

    const data = (await res.json()) as {
      success?: boolean
      hostname?: string
      action?: string
      "error-codes"?: string[]
      metadata?: { result_with_testing_key?: boolean }
    }

    if (data.success !== true) {
      return {
        ok: false,
        reason: `rejected: ${(data["error-codes"] ?? []).join(",") || "unknown"}`,
      }
    }
    /*
     * Cloudflare's documented ALWAYS-PASS test keys answer with
     * `hostname: "example.com"` and no `action` at all, so the two checks below
     * would reject every local comment. Cloudflare marks those responses
     * explicitly, and that marker cannot appear for a real sitekey — so trust
     * it, and skip the checks that the test keys structurally cannot satisfy.
     *
     * Loud, because a production Worker configured with a test secret would be
     * accepting anything, and that should be impossible to miss in the logs.
     */
    if (data.metadata?.result_with_testing_key === true) {
      console.warn(
        "turnstile: TEST KEY in use — action and hostname checks skipped. " +
          "This must never appear in production.",
      )
      return { ok: true }
    }

    if (data.action !== expectedAction) {
      return { ok: false, reason: `action mismatch: got ${data.action ?? "none"}` }
    }
    if (!data.hostname || !allowedHostnames.includes(data.hostname)) {
      return { ok: false, reason: `hostname not allowed: ${data.hostname ?? "none"}` }
    }
    return { ok: true }
  } catch (err) {
    const aborted = (err as Error)?.name === "AbortError"
    return { ok: false, reason: aborted ? "siteverify timed out" : "siteverify unreachable" }
  } finally {
    clearTimeout(timer)
  }
}

/**
 * Hosts a Turnstile token may legitimately have been solved on.
 *
 * `TURNSTILE_HOSTNAMES` (comma separated) pins this explicitly. With it unset
 * the list is the configured site plus the host actually serving this request —
 * which is what makes the bootstrap sequence work: the first deployments live
 * on *.workers.dev, long before DNS points at the custom domain, and a check
 * hardcoded to mandulaj.hu would reject every comment there with a misleading
 * "verification failed".
 *
 * It stays strict in the sense that matters: the token must come from a host we
 * are actually serving, never from someone else's page.
 */
export function allowedTurnstileHostnames(env: Env, request: Request): string[] {
  const pinned = env.TURNSTILE_HOSTNAMES?.trim()
  if (pinned) {
    return pinned
      .split(",")
      .map((h: string) => h.trim().toLowerCase())
      .filter(Boolean)
  }

  const hosts = new Set<string>()
  try {
    hosts.add(new URL(request.url).hostname.toLowerCase())
  } catch {
    /* unreachable in a Worker, but never throw from here */
  }
  if (env.SITE_ORIGIN) {
    try {
      hosts.add(new URL(env.SITE_ORIGIN).hostname.toLowerCase())
    } catch {
      /* a malformed SITE_ORIGIN must not disable verification */
    }
  }
  return [...hosts]
}

/**
 * Fire-and-forget Telegram notification. Never throws and never blocks the
 * response — a comment must still be accepted if Telegram is unreachable.
 */
export function telegramMessagePayload(chat: string, text: string, thread?: string) {
  const rawThread = thread?.trim()
  let messageThreadId: number | undefined

  if (rawThread) {
    if (!/^[1-9]\d*$/.test(rawThread)) return null
    const parsed = Number(rawThread)
    if (!Number.isSafeInteger(parsed)) return null
    messageThreadId = parsed
  }

  return {
    chat_id: chat,
    text,
    parse_mode: "HTML",
    disable_web_page_preview: true,
    ...(messageThreadId === undefined ? {} : { message_thread_id: messageThreadId }),
  }
}

/** Returns the generated page title, decoded for use outside HTML. */
export function pageTitleFromHtml(html: string, fallback: string): string {
  const raw = html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1]
  if (!raw) return fallback

  const named: Record<string, string> = {
    amp: "&",
    apos: "'",
    gt: ">",
    lt: "<",
    quot: '"',
  }
  const decoded = raw.replace(/&(?:#(\d+)|#x([0-9a-f]+)|([a-z]+));/gi, (entity, dec, hex, name) => {
    if (dec) return String.fromCodePoint(Number(dec))
    if (hex) return String.fromCodePoint(Number.parseInt(hex, 16))
    return named[String(name).toLowerCase()] ?? entity
  })
  return decoded.replace(/\s+/g, " ").trim() || fallback
}

/** One-sentence comment summary followed by the existing deep link. */
export function telegramCommentText(title: string, name: string, comment: string, url: string) {
  return (
    `💬 On <b>${esc(title)}</b>, <b>${esc(name)}</b> commented: “${esc(comment.slice(0, 500))}”\n\n` +
    esc(url)
  )
}

export async function notifyTelegram(env: Env, text: string): Promise<void> {
  const { TELEGRAM_BOT_TOKEN: token, TELEGRAM_CHAT_ID: chat, TELEGRAM_THREAD_ID: thread } = env
  if (!token || !chat) return
  const payload = telegramMessagePayload(chat, text, thread)
  if (!payload) {
    console.warn(
      JSON.stringify({
        message: "telegram notification skipped",
        reason: "invalid TELEGRAM_THREAD_ID",
      }),
    )
    return
  }
  try {
    await fetch(`https://api.telegram.org/bot${token}/sendMessage`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    })
  } catch {
    /* notification is best-effort */
  }
}

/** Escapes text for safe interpolation into Telegram's HTML parse mode. */
export const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
